name: Schedule

permissions:
  contents: write

on:
  schedule:
    - cron: '0,15,30,45 * * * *'
  workflow_dispatch:

jobs:
  run_notebook:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python & Jupyter
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ipykernel jupyter papermill nbformat
          python -m ipykernel install --user --name python3 --display-name python3

      - name: Execute notebook
        run: |
          papermill --kernel python3 Holy_Grail.ipynb output.ipynb

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Scheduled run on $(date)"
          file_pattern: output.ipynb

      - name: Send last cell output to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: ./send_to_discord.sh

