name: Schedule

permissions:
  contents: write

on:
  schedule:
    - cron: '*/5 * * * *'        # every 15 minutes (UTC)
  workflow_dispatch: {}           # manual trigger

concurrency:
  group: cron-${{ github.workflow }}
  cancel-in-progress: false       # queue one pending run; don’t cancel in-flight

jobs:
  run_notebook:
    runs-on: self-hosted

    steps:
      - name: Gate until first run
        uses: actions/github-script@v6
        id: gate
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Always run immediately if manually triggered
            if (context.eventName === 'workflow_dispatch') {
              core.setOutput('skip', 'false');
              return;
            }
            // Otherwise (schedule), compare timestamps
            const now     = new Date();
            const startAt = new Date('2025-06-09T03:00:00Z');
            core.setOutput('skip', now < startAt ? 'true' : 'false');

      - name: Skip early runs
        if: steps.gate.outputs.skip == 'true'
        run: echo "🔒 Waiting for first run time..."

      - name: Checkout repository
        if: steps.gate.outputs.skip == 'false'
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python & Jupyter
        if: steps.gate.outputs.skip == 'false'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ipykernel jupyter papermill nbformat
          python -m ipykernel install --user --name python3 --display-name python3

      - name: Execute notebook
        if: steps.gate.outputs.skip == 'false'
        run: |
          papermill --kernel python3 Holy_Grail.ipynb output.ipynb

      - name: Commit results
        if: steps.gate.outputs.skip == 'false'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Scheduled run on $(date)"
          file_pattern: output.ipynb

      - name: Make script executable
        if: steps.gate.outputs.skip == 'false'
        run: chmod +x ./send_to_discord.sh

      - name: Send formatted table to Discord
        if: steps.gate.outputs.skip == 'false'
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [[ ! -f summary.txt ]]; then
            echo "⚠️ summary.txt not found, aborting."
            exit 1
          fi
      
          # Read the summary
          FORMATTED=$(cat summary.txt)
      
          # Safely wrap in triple backticks
          BLOCKED=$(cat <<EOF
          \`\`\`
          $FORMATTED
          \`\`\`
          EOF
          )
      
          # JSON-encode
          PAYLOAD=$(printf '%s' "$BLOCKED" | python3 -c 'import sys,json; print(json.dumps({"content": sys.stdin.read().strip()}))')
      
          echo "→ PAYLOAD: $PAYLOAD"
      
          curl -X POST \
               -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               "$WEBHOOK_URL"

