name: Schedule
on:
  schedule:
    - cron: '0,15,30,45 * * * *'
  workflow_dispatch:

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ipykernel jupyter
          python -m ipykernel install --user --name python3 --display-name python3

      - name: Execute notebook
        run: |
          papermill --kernel python3 Holy_Grail.ipynb output.ipynb

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Scheduled run on $(date)"
          file_pattern: output.ipynb

      - name: Send report to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST $WEBHOOK_URL \
            -F "payload_json={\"content\":\"📋 **Active Orders Report**\",\"username\":\"TradeBot\"}" \
            -F "file=@output.ipynb"
