name: Schedule
on:
  schedule:
    - cron: '0,15,30,45 * * * *'
  workflow_dispatch:
jobs:
  run_notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute notebook
        run: |
          papermill Holy_Grail.ipynb output.ipynb
      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Scheduled run on $(date)"
          file_pattern: output.ipynb
